routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UsersController::class, 'index'])->name('users');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
});

app/Http/Controllers/Profile/AccountController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Enums\AccountType;
use App\Http\Controllers\Controller;
use App\Http\Requests\AccountMakeRequest;
use App\Models\Account;
use App\Services\AccountService;

class AccountController extends Controller
{
    private AccountService $service;

    public function __construct(AccountService $service)
    {
        $this->service = $service;
    }

    public function accounts()
    {
        return view('pages.profile.accounts.showAll', [
            'accounts' => auth()->user()->accounts,
        ]);
    }

    public function store(AccountMakeRequest $request)
    {
        $this->service->store($request->validated());

        return redirect()->route('accounts.show');
    }

    public function select(Account $account)
    {
        $expenses = $account->expenses;
        $incomes = $account->incomes;

        return view('pages.profile.accounts.showSelected', [
            'account' => $account,
            'expenses' => $expenses,
            'incomes' => $incomes,
        ]);
    }

    public function delete(Account $account)
    {
        $account->delete();

        return back();
    }

    public function newRecord(Account $account, AccountType $type)
    {
        abort_if($type !== 'income' && $type !== 'expense', 401);

        if ($type === 'income') {
            $userTypes = auth()->user()->incomeTypes;
        } else {
            $userTypes = auth()->user()->expenseTypes;
        }

        return view('pages.profile.accounts.newRecord', [
            'account' => $account,
            'type' => $type,
            'types' => $userTypes,
        ]);
    }
}

app/Http/Controllers/Profile/CardController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;

class CardController extends Controller
{
    public function cards()
    {
        return view('pages.profile.cards.showAll', [
            'cards' => auth()->user()->bankCards,
        ]);
    }

    public function add()
    {
        return view('pages.profile.cards.add');
    }
}

app/Http/Controllers/Profile/CategoryController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Models\Account;
use App\Models\IncomeCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function add(Request $request, Account $account, string $type)
    {
        if ($type === 'income') {
            IncomeCategory::create([
                'user_id' => auth()->id(),
                'name' => $request['name'],
            ]);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/Profile/DashboardController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Services\DashboardService;

class DashboardController extends Controller
{
    private DashboardService $service;

    public function __construct(DashboardService $service)
    {
        $this->service = $service;
    }

    public function dashboard()
    {
        return view('pages.profile.dashboard', [
            'accounts' => $this->service->getAccounts(),
        ]);
    }
}

app/Http/Controllers/Profile/FamilyController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Http\Requests\JoinFamilyRequest;
use App\Models\Family;
use App\Models\User;
use App\Services\FamilyService;

class FamilyController extends Controller
{
    private FamilyService $service;

    public function __construct(FamilyService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        return view('pages.profile.families.index', [
            'familyMembers' => $this->service->getFamilyMembers(),
            'isCreator' => auth()->user()->isFamilyCreator(),
        ]);
    }

    public function create()
    {
        auth()->user()->createNewFamily();

        return back();
    }

    public function kick(User $member)
    {
        $this->service->kickMember($member);

        return back();
    }

    public function join(JoinFamilyRequest $request)
    {
        $family = Family::whereInvitationCode($request->validated()['code'])->first();

        if (! $family) {
            return back();
        }

        auth()->user()->joinFamily($family);

        return redirect()->route('family.index');
    }
}

app/Http/Controllers/Profile/OrganizationController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;

class OrganizationController extends Controller
{
    public function index()
    {
        return view('pages.profile.organizations.index');
    }
}

app/Http/Controllers/Profile/SubscriptionController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Models\SubscriptionPlan;

class SubscriptionController extends Controller
{
    public function index()
    {
        return view('pages.profile.subscriptions.index', [
            'currentSubscription' => auth()->user()->subscriptionPlan,
            'subscriptions' => SubscriptionPlan::all(),
        ]);
    }

    public function change(SubscriptionPlan $subscription)
    {
        auth()->user()->changeSubscriptionPlan($subscription);

        return redirect()->back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/pages/profile/subscriptions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Subscription') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="overflow-hidden bg-white shadow-xl sm:rounded-lg">
                <div class="relative overflow-x-auto">
                    <div class="w-full text-sm text-left text-gray-500 rtl:text-right dark:text-gray-400">
                        <div class="p-5" x-data='{showAll:false}'>
                            <div>
                                <div x-show='!showAll'>
                                    <div class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                                        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                            {{$currentSubscription->name}}
                                        </h5>
                                        <p class="font-normal text-gray-700 dark:text-gray-400">
                                            {{$currentSubscription->description}}
                                        </p>
                                    </div>
                                </div>
                                <div x-show='showAll' x-cloak>
                                    <div class="flex gap-3">
                                        @foreach ($subscriptions as $subscription)
                                        @php
                                        $isActive = $subscription->is($currentSubscription);
                                        // $isActive = $subscription->id === $currentSubscription->id;
                                        @endphp
                                        <div class="flex flex-col justify-between max-w-sm p-6 bg-white border {{$isActive ? 'border-green-400' : 'border-gray-200'}}  rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                                            <h5 class="flex justify-between mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
                                                {{$subscription->name}}
                                                <span class="{{$isActive ? 'border border-green-400 bg-green-100 text-green-800' : 'border border-red-400 bg-red-100 text-red-800'}} h-fit  text-xs font-medium me-2 px-2.5 py-0.5 rounded ">
                                                    {{$isActive ? 'Active' : 'Inactive'}}
                                                </span>
                                            </h5>
                                            <p class="font-normal text-gray-700 dark:text-gray-400">
                                                {{$subscription->description}}
                                            </p>
                                            <div class="mt-3">
                                                @if ($isActive)
                                                <button type="button" disabled class="text-white bg-gray-400 cursor-not-allowed focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none">
                                                    Selected
                                                </button>
                                                @else
                                                <form action="{{route('subscription.change',['subscription'=>$subscription->id])}}" method="post">
                                                    @csrf
                                                    <button type="submit" class="text-white  bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 focus:outline-none">
                                                        Select
                                                    </button>
                                                </form>
                                                @endif
                                            </div>
                                        </div>
                                        @endforeach
                                    </div>
                                </div>
                            </div>

                            <div class="flex mt-5">
                                <div x-show='!showAll'>
                                    <button type="button" x-on:click='showAll = true' class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                                        Change Plan
                                    </button>
                                </div>
                                <div x-show='showAll' x-cloak>
                                    <button type="button" x-on:click='showAll = false' class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800">
                                        Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>