routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UsersController::class, 'index'])->name('users');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
});

app/Http/Controllers/Profile/AccountController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Enums\AccountType;
use App\Http\Controllers\Controller;
use App\Http\Requests\AccountMakeRequest;
use App\Models\Account;
use App\Services\AccountService;

class AccountController extends Controller
{
    private AccountService $service;

    public function __construct(AccountService $service)
    {
        $this->service = $service;
    }

    public function accounts()
    {
        return view('pages.profile.accounts.showAll', [
            'accounts' => auth()->user()->accounts,
        ]);
    }

    public function store(AccountMakeRequest $request)
    {
        $this->service->store($request->validated());

        return redirect()->route('accounts.show');
    }

    public function select(Account $account)
    {
        $expenses = $account->expenses;
        $incomes = $account->incomes;

        return view('pages.profile.accounts.showSelected', [
            'account' => $account,
            'expenses' => $expenses,
            'incomes' => $incomes,
        ]);
    }

    public function delete(Account $account)
    {
        $account->delete();

        return back();
    }

    public function newRecord(Account $account, AccountType $type)
    {
        abort_if($type !== 'income' && $type !== 'expense', 401);

        if ($type === 'income') {
            $userTypes = auth()->user()->incomeTypes;
        } else {
            $userTypes = auth()->user()->expenseTypes;
        }

        return view('pages.profile.accounts.newRecord', [
            'account' => $account,
            'type' => $type,
            'types' => $userTypes,
        ]);
    }
}

app/Http/Controllers/Profile/CardController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;

class CardController extends Controller
{
    public function cards()
    {
        return view('pages.profile.cards.showAll', [
            'cards' => auth()->user()->bankCards,
        ]);
    }

    public function add()
    {
        return view('pages.profile.cards.add');
    }
}

app/Http/Controllers/Profile/CategoryController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Models\Account;
use App\Models\IncomeCategory;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function add(Request $request, Account $account, string $type)
    {
        if ($type === 'income') {
            IncomeCategory::create([
                'user_id' => auth()->id(),
                'name' => $request['name'],
            ]);
        }

        return redirect()->back();
    }
}

app/Http/Controllers/Profile/DashboardController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Services\DashboardService;

class DashboardController extends Controller
{
    private DashboardService $service;

    public function __construct(DashboardService $service)
    {
        $this->service = $service;
    }

    public function dashboard()
    {
        return view('pages.profile.dashboard', [
            'accounts' => $this->service->getAccounts(),
        ]);
    }
}

app/Http/Controllers/Profile/FamilyController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Http\Requests\JoinFamilyRequest;
use App\Models\Family;
use App\Models\User;
use App\Services\FamilyService;

class FamilyController extends Controller
{
    private FamilyService $service;

    public function __construct(FamilyService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        return view('pages.profile.families.index', [
            'familyMembers' => $this->service->getFamilyMembers(),
            'isCreator' => auth()->user()->isFamilyCreator(),
        ]);
    }

    public function create()
    {
        auth()->user()->createNewFamily();

        return back();
    }

    public function kick(User $member)
    {
        $this->service->kickMember($member);

        return back();
    }

    public function join(JoinFamilyRequest $request)
    {
        $family = Family::whereInvitationCode($request->validated()['code'])->first();

        if (! $family) {
            return back();
        }

        auth()->user()->joinFamily($family);

        return redirect()->route('family.index');
    }
}

app/Http/Controllers/Profile/OrganizationController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;

class OrganizationController extends Controller
{
    public function index()
    {
        return view('pages.profile.organizations.index');
    }
}

app/Http/Controllers/Profile/SubscriptionController.php
<?php

namespace App\Http\Controllers\Profile;

use App\Http\Controllers\Controller;
use App\Models\SubscriptionPlan;

class SubscriptionController extends Controller
{
    public function index()
    {
        return view('pages.profile.subscriptions.index', [
            'currentSubscription' => auth()->user()->subscriptionPlan,
            'subscriptions' => SubscriptionPlan::all(),
        ]);
    }

    public function change(SubscriptionPlan $subscription)
    {
        auth()->user()->changeSubscriptionPlan($subscription);

        return redirect()->back();
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.admin');
    }
}

resources/views/pages/profile/admin/users.blade.php
<x-admin-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="overflow-hidden bg-white shadow-xl sm:rounded-lg">
        <div class="relative overflow-x-auto">
            <table class="w-full text-sm text-left text-gray-500 rtl:text-right dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            #
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Name
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Email
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $index => $user)
                    @unless($user->is(auth()->user()))
                    {{-- @unless ($user->id === auth()->id()) --}}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ $index + 1 }}
                        </th>
                        <td class="px-6 py-4">
                            {{$user->name}}
                        </td>

                        <td class="px-6 py-4">
                            {{$user->email}}
                        </td>
                    </tr>
                    @endunless
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</x-admin-layout>