routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
Route::get('/users', [UsersController::class, 'index'])->name('users');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/pages/main_website/about.blade.php
<x-guest-layout>

</x-guest-layout>

resources/views/pages/main_website/contact.blade.php
<x-guest-layout>

</x-guest-layout>

resources/views/pages/main_website/features.blade.php
<x-guest-layout>

</x-guest-layout>

resources/views/pages/main_website/license.blade.php
<x-guest-layout>
    <section class="pt-24">
        <div class="max-w-screen-lg mx-auto space-y-12 bg-purple-200 border rounded-lg lg:space-y-20 lg:my-10 ">
            <div class="px-4 py-8 lg:py-5 lg:px-6">
                <div class="items-center gap-8 lg:grid lg:grid-cols-2 xl:gap-2">
                    <div class="text-gray-500 sm:text-lg dark:text-gray-400">

                    </div>
                </div>
            </div>
        </div>
    </section>
</x-guest-layout>

resources/views/pages/main_website/plans.blade.php
<x-guest-layout>
    <section class="pt-24 space-y-10">
        @foreach ($plans as $index => $plan)
        <div class="max-w-screen-lg mx-auto space-y-12 bg-purple-100 border rounded-lg hover:bg-purple-300 hover:shadow-2xl hover:border-purple-500 lg:space-y-20 lg:my-10 ">
            <a href="{{route('subscription.index')}}">
                <div class="px-4 py-8 lg:py-5 lg:px-6 sm:mx-5">
                    <div class="items-center gap-8 lg:grid lg:grid-cols-2 xl:gap-2">
                        <img class="hidden mb-4 rounded-lg w-96 lg:mb-0 lg:flex" src="{{asset('img/subscription_plan/plan_cover_'.($index + 1).'.png')}}" alt="Plan #{{ $index + 1 }} Image">
                        <div class="text-gray-500 sm:text-lg dark:text-gray-400">
                            <h2 class="mb-4 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">
                                {{ $plan->name }}
                            </h2>
                            <p class="mb-8 font-light lg:text-xl">
                                {{ $plan->description }}
                            </p>
                            <ul role="list" class="pt-8 space-y-5 border-t border-gray-200 my-7 dark:border-gray-700">
                                @foreach ($plan->features as $feature)
                                <li class="flex space-x-3">
                                    <svg class="flex-shrink-0 w-5 h-5 text-purple-500 dark:text-purple-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">
                                        </path>
                                    </svg>
                                    <span class="text-base font-medium leading-tight text-gray-900 dark:text-white">
                                        {{ $feature->name }}
                                    </span>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        @endforeach
    </section>
</x-guest-layout>

resources/views/pages/main_website/policy.blade.php
<x-guest-layout>
    <section class="pt-24">
        <div class="max-w-screen-lg mx-auto space-y-12 bg-purple-200 border rounded-lg lg:space-y-20 lg:my-10 ">
            <div class="px-4 py-8 lg:py-5 lg:px-6">
                <div class="items-center gap-8 lg:grid lg:grid-cols-2 xl:gap-2">
                    <div class="text-gray-500 sm:text-lg dark:text-gray-400">

                    </div>
                </div>
            </div>
        </div>
    </section>
</x-guest-layout>

resources/views/pages/main_website/terms.blade.php
<x-guest-layout>
    <section class="pt-20 bg-white dark:bg-gray-900">
        <div class="max-w-screen-xl px-4 py-8 mx-auto lg:py-24 lg:px-6">
            <div class="max-w-screen-md mx-auto mb-8 text-center lg:mb-12">
                <h2 class="mb-4 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white">
                    Terms of Service
                </h2>
                <p class="mb-5 font-light text-gray-500 sm:text-xl dark:text-gray-400">
                    By accessing and using {{ config('app.name') }}, you agree to comply with and be bound by the following terms and conditions.
                    If you do not agree with any of these terms, please do not use our services.
                </p>
            </div>

            <div>
                <ol class="space-y-5 text-gray-500 list-decimal list-inside dark:text-gray-400">
                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            Use of the Service
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    You must be at least 18 years old to use our services.
                                </span>
                            </li>
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    You agree not to use our services for any illegal or unauthorized purpose.
                                </span>
                            </li>
                        </ul>
                    </li>

                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            User Account
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    You are responsible for maintaining the security of your account and password.
                                </span>
                            </li>
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    You agree not to share your account access with others.
                                </span>
                            </li>
                        </ul>
                    </li>

                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            Content
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    Users are solely responsible for the content they post on the platform.
                                </span>
                            </li>
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    We reserve the right to remove any content that violates our policies.
                                </span>
                            </li>
                        </ul>
                    </li>

                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            Privacy
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    Your privacy is important to us. Please review our Privacy
                                    Policy to understand how we collect and use your information.
                                </span>
                            </li>
                        </ul>
                    </li>

                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            Termination
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    We reserve the right to terminate or suspend your account at our sole discretion without prior notice.
                                </span>
                            </li>
                        </ul>
                    </li>

                    <li class="text-2xl">
                        <span class="font-semibold text-gray-900 dark:text-white">
                            Changes to Terms
                        </span>
                        <ul class="space-y-1 text-gray-500 list-disc list-inside dark:text-gray-400">
                            <li>
                                <span class="text-base font-semibold text-gray-900 dark:text-white">
                                    We may revise these terms at any time without notice. By continuing to use our services,
                                    you agree to be bound by the updated terms.
                                </span>
                            </li>
                        </ul>
                    </li>
                </ol>
            </div>
        </div>
    </section>
</x-guest-layout>